<?php
/**
 * @file
 * File containing the implemented hooks.
 */

/**
 * Implements hook_help().
 */
function social_stats_help($path, $arg) {
  $help_text = '';
  switch ($path) {
    case 'admin/help#social_stats':
      $help_text = '<p>' . t('This module provides an API to get the social statistics of the nodes of the selected content types. The data includes number of shares of a particular node on Facebook, Twitter, LinkedIn, Google Plus. This module does a collection of data on cron run. Using modules like Elysia Cron this can be set to some convinient time (for e.g. once or twice a day).') . '</p><p>' . t('Use Social Stats Views module for integration of this data in the Views module : like sorting according to the number of shares, using the number of shares as a field, having a filter criteria with this data, etc.') . '</p>';
      break;
  }
  return $help_text;
}

/**
 * Implements hook_menu().
 */
function social_stats_menu() {
  $items['admin/config/services/social-stats/settings'] = array(
    'title' => 'Social Statistics',
    'description' => 'Administrative settings for social stats module',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('social_stats_content_types_form'),
    'access arguments' => array('Administer Social Stats'),
    'file' => 'social_stats.admin.inc',
  );
  return $items;
}

/**
 * Implements hook_permission().
 */
function social_stats_permission() {
  return array(
    'Administer Social Stats' => array(
      'title' => t('Administer my module'),
      'description' => t('Perform administration tasks for my module.'),
    ),
  );
}

/**
 * Fetch the data from Facebook and save it to local table.
 *
 * @param array $node
 *   Contains $node->nid.
 * @param string $node_path
 *   The URL alias.
 */
function _social_stats_facebook($node, $node_path = '') {
  $facebook_total = 0;

  $fql_query  = 'SELECT share_count, like_count, comment_count, total_count ';
  $fql_query .= "FROM link_stat WHERE url='" . $node_path . "'";

  // TODO: Implement multi-query
  // https://developers.facebook.com/docs/technical-guides/fql/
  $fql_queries = array('query1' => $fql_query);
  $params = array(
    'q' => json_encode($fql_queries),
    'format' => 'json',
    // 'access_token' => $access_token
  );

  $request_url = 'https://graph.facebook.com/fql?' . http_build_query($params);

  $fql_response = @drupal_http_request($request_url);


  if (!empty($fql_response->error)) {
    watchdog(t('Social Stats'),
      'Problem updating data from Facebook for %node_path. Error: %err',
      array('%node_path' => $node_path, '%err' => $fql_response->error),
      NULL, WATCHDOG_ERROR);
  }
  else {
    $fql_data = json_decode($fql_response->data);
    foreach ($fql_data->data as $fql_data_row) {
      $facebook_data = $fql_data_row->fql_result_set;
      // Only update table if counter > 0
      if (intval($facebook_data[0]->total_count)) {
        db_merge('social_stats_facebook')
        ->key(array('nid' => $node->nid))
        ->fields(array(
          'node_type' => $node->type,
          'fb_likes' => intval($facebook_data[0]->like_count),
          'fb_shares' => intval($facebook_data[0]->share_count),
          'fb_comments' => intval($facebook_data[0]->comment_count),
          'fb_total' => intval($facebook_data[0]->total_count),
        ))
        ->execute();
        return $facebook_data[0]->total_count;
      }
      return 0;
    }
  }
}

/**
 * Implements hook_cron().
 */
function social_stats_cron() {
  // Get list of content types in the site.
  $node_types = node_type_get_types();
  $content_types = array();
  foreach ($node_types as $types) {
    $variable = variable_get($types->type);
    if ($variable['Facebook']    ||
        $variable['Twitter']     ||
        $variable['Google Plus'] ||
        $variable['LinkedIn']) {
      $content_types[] = $types->type;
    }
  }

  // Fetch node id and type for the content types,
  // which has atleast one social media selected.
  $query = db_select('node', 'n')
            ->fields('n', array('nid', 'type'))
            ->condition('n.type', empty($content_types) ? '0' : $content_types)
            ->execute();
  while ($result = $query->fetchObject()) {
    $facebook_total = 0;
    $twitter_shares = 0;
    $linkedin_shares = 0;
    $google_plusone = 0;
    $variable = variable_get($result->type);
    $node_path = url('node/' . $result->nid, array('absolute' => TRUE));

    // Getting data from Facebook for nodes of the selected node type.
    if ($variable['Facebook']) {
      $facebook_total = _social_stats_facebook($result, $node_path);
    }

    // Getting data from Twitter for nodes of selected node type.
    if ($variable['Twitter']) {
      // Write a query to fetch the data from Twitter.
      $tweets_query = 'http://urls.api.twitter.com/1/urls/count.json?url=';
      $tweets_query .= $node_path;
      $tweets_response = drupal_http_request($tweets_query);
      $tweets_data = json_decode($tweets_response->data);
      db_merge('social_stats_twitter')
      ->key(array('nid' => $result->nid))
      ->fields(array(
        'node_type' => $result->type,
        'tweets' => $tweets_data->count,
      ))
      ->execute();
      $twitter_shares = $tweets_data->count;
    }

    // Getting data from LinkedIn for nodes of selected node type.
    if ($variable['LinkedIn']) {
      // Write a query to fetch the data from LinkedIn.
      $linkedin_query = 'http://www.linkedin.com/countserv/count/share?';
      $linkedin_query .= 'format=json&url=' . $node_path;
      $linkedin_response = drupal_http_request($linkedin_query);
      $linkedin_data = json_decode($linkedin_response->data);
      db_merge('social_stats_linkedin')
      ->key(array('nid' => $result->nid))
      ->fields(array(
        'node_type' => $result->type,
        'linkedin_shares' => $linkedin_data->count,
      ))
      ->execute();
      $linkedin_shares = $linkedin_data->count;
    }

    // Getting data from Google Plus for nodes of selected node type.
    if ($variable['Google Plus']) {
      // Build the JSON data for the API request.
      $data['method'] = 'pos.plusones.get';
      $data['id'] = 'p';
      $data['params']['nolog'] = TRUE;
      $data['params']['id'] = $node_path;
      $data['params']['source'] = 'widget';
      $data['params']['userId'] = '@viewer';
      $data['params']['groupId'] = '@self';
      $data['jsonrpc'] = '2.0';
      $data['key'] = 'p';
      $data['apiVersion'] = 'v1';

      $url = 'https://clients6.google.com/rpc?key=AIzaSyCKSbrvQasunBoV16zDH9R33D88CeLr9gQ';
      $options['data'] = json_encode($data);
      $options['method'] = 'POST';
      $options['headers']['Content-Type'] = 'application/json';

      $request = drupal_http_request($url, $options);
      if (empty($request->error) && !empty($request->data)) {
        $request->data = json_decode($request->data);
        if (isset($request->data->result->metadata->globalCounts->count)) {
          $gplus_count = $request->data->result->metadata->globalCounts->count;
          db_merge('social_stats_gplus')
            ->key(array('nid' => $result->nid))
            ->fields(array(
              'node_type' => $result->type,
              'plusone' => $gplus_count,
            ))
            ->execute();
          $google_plusone = $gplus_count;
        }
      }
    }

    $count_total = $facebook_total + $twitter_shares;
    $count_total += $linkedin_shares + $google_plusone;
    // Adding the total data from all above to get total virality.
    db_merge('social_stats_total')
    ->key(array('nid' => $result->nid))
    ->fields(array(
      'node_type' => $result->type,
      'total_virality' => $count_total,
    ))
    ->execute();
  }
}

/**
 * Implements hook_node_delete().
 */
function social_stats_node_delete($node) {
  // Delete all the social data on node deletion.
  db_delete('social_stats_facebook')
    ->condition('nid', $node->nid)
    ->execute();
  db_delete('social_stats_twitter')
    ->condition('nid', $node->nid)
    ->execute();
  db_delete('social_stats_linkedin')
    ->condition('nid', $node->nid)
    ->execute();
  db_delete('social_stats_gplus')
    ->condition('nid', $node->nid)
    ->execute();
  db_delete('social_stats_total')
    ->condition('nid', $node->nid)
    ->execute();
}
